version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3005:3005"
    runtime: nvidia
    volumes:
      - ./src:/src
    #links:
    #  - redis
    #  - nginx
    restart: on-failure
    command: node /src/app.js
    networks:
      - app-network


networks:
  app-network:
    driver: bridge